### ISSUE TITLE
i have some problem

### ISSUE THREAD

**Issue by jackft2** [Pangoraw/PaDiM#3]
1. what is padeep.log?
2. what PARAMS_PATH do I need to write?

**Comment by SDJustus** [comment]
1. padeep.log is the log file, generated while training... take a look at the logger in https://github.com/Pangoraw/PaDiM/blob/main/examples/padeep.py to see what is logged
2. PARAMS_PATH is the path, where your training results are saved (i.e. results/your_file_name.pickle). See lines 102-104 in https://github.com/Pangoraw/PaDiM/blob/main/examples/padeep.py

**Comment by Pangoraw** [comment]
Thanks for answering @SDJustus!
