### ISSUE TITLE
Anomaly Heatmaps

### ISSUE THREAD

**Issue by SDJustus** [Pangoraw/PaDiM#5]
Hi,

is there a way to get the anomaly heatmaps from your code?

Best regards,
Justus

**Comment by Pangoraw** [comment]
`padim.predict(..)` returns the mahalanobis distances for each patch of the image. You can resize it to a square matrix to see the unormalized anomaly map. So you can do something like that:

```python
import math
import matplotlib.pyplot
distances = padim.predict(img.unsqueeze(0))
w = math.sqrt(distances.numel())
amap = distances.view(w, w)
plt.imshow(amap)
plt.show()
```

**Comment by Pangoraw** [comment]
![image](https://user-images.githubusercontent.com/9824244/121209768-6c64a580-c87b-11eb-9fb2-8d350310ae80.png)

Here is an example notebook where the input is 416x416 so the backbone outputs 104x104 anomaly maps

**Comment by SDJustus** [comment]
Thank you again for your super fast work. I appreciate your effort very much!

**Comment by rishabh-akridata** [comment]
@Pangoraw Why are we using Gaussian blurring as a preprocessing step for the amap? Is it just for visualization or is there any specific reason for doing that?
