### ISSUE TITLE
Gaussian and Mahalanobis distance

### ISSUE THREAD

**Issue by Leonardo0325** [Pangoraw/PaDiM#8]
Hello, I would like to ask a question. Now I have found that the Gaussian distribution at certain points exhibits a double Gaussian distribution, and there may be deviations when calculating the mean and covariance. I would like to distinguish the channels that conform to the double Gaussian distribution, and then calculate the minimum Mahalanobis distance separately from the two distributions. Do you have any ideas about this?

**Comment by Pangoraw** [comment]
Hello, you may want to test other PaDiM variants present in this repository such as [PaDiMSVDD](https://github.com/Pangoraw/PaDiM/blob/76f757fd51c46abda1ced5a26c2865c6d91a8cca/padim/padim_svdd.py#L21) or [PaDiMNVP](https://github.com/Pangoraw/PaDiM/blob/b8e3e2466612f753d8342c744d41b9a8a7fb6e58/padim/panf.py#L34) which both use deep distribution estimators to compute the out-of-distribution score (Mahalanobis distance in the original PaDiM).
We have found, that they are better at handling multi-modal normal distributions than the Gaussian padim.

**Comment by LonglongaaaGo** [comment]
Hi @Pangoraw ,

Thank you so much for your awesome work!
What is the paper from, for [PaDiMNVP](https://github.com/Pangoraw/PaDiM/blob/b8e3e2466612f753d8342c744d41b9a8a7fb6e58/padim/panf.py#L34)?

Thanks!

**Comment by Pangoraw** [comment]
This is the paper in question with more details: [ Weakly Supervised Detection of Marine Animals in High Resolution Aerial Images ](https://www.mdpi.com/2072-4292/14/2/339)

**Comment by LonglongaaaGo** [comment]
> This is the paper in question with more details: [ Weakly Supervised Detection of Marine Animals in High Resolution Aerial Images ](https://www.mdpi.com/2072-4292/14/2/339)

@Pangoraw  Thank you so much! I found your published papers interesting, and I hope we can work together in the future.
