### ISSUE TITLE
Description of the semmacape data set

### ISSUE THREAD

**Issue by mayongfei1** [Pangoraw/PaDiM#9]
Thank you very much for your great work.
In order to reproduce your work, I would like to figure out the structure of your semmacape data set and the format of GT boxes. Could you please provide a description of the data set?

**Comment by Pangoraw** [comment]
Hello, IIRC GT Files have the following format:

```
x1 y1 x2 y2 s
```

where $x_1,y_1,x_2,y_2\in[0,1]^4$ and s is one of the following label:

https://github.com/Pangoraw/PaDiM/blob/76f757fd51c46abda1ced5a26c2865c6d91a8cca/examples/test_semmacape.py#L18-L35

**Comment by mayongfei1** [comment]
Thank you very much !
